# version: "3.9"

# services:
#   web:
#     build: .
#     container_name: python_app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_USER=postgres
#       - DB_PASSWORD=yourpassword
#       - DB_NAME=mydatabase

#   db:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: yourpassword
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:


version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  # SQL Server 2022 container image
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y                # Must accept license
      - SA_PASSWORD=YourStrong!Passw0rd  # Change to a strong password
    ports:
      - "11433:1433"                  # HostPort:ContainerPort
    volumes:
      - sqlserver_data:/var/opt/mssql # Persist data between restarts
    restart: unless-stopped

volumes:
  sqlserver_data:
